// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOFndxRVB9neZWd112bCOBTHvhnHpIObY',
    appId: '1:784088242608:web:a8e67b54c56a0fd0c6de75',
    messagingSenderId: '784088242608',
    projectId: 'bidbird-5164d',
    authDomain: 'bidbird-5164d.firebaseapp.com',
    storageBucket: 'bidbird-5164d.firebasestorage.app',
    measurementId: 'G-8BEHKWMX0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDts4NYB4_XEncwNF79CZKPI9yGzHiteMw',
    appId: '1:784088242608:android:bb7443aabe3aad13c6de75',
    messagingSenderId: '784088242608',
    projectId: 'bidbird-5164d',
    storageBucket: 'bidbird-5164d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSYapH_Krufq0mdW5SfBGAXAjIT1tvI5o',
    appId: '1:784088242608:ios:681c31c88488c8d9c6de75',
    messagingSenderId: '784088242608',
    projectId: 'bidbird-5164d',
    storageBucket: 'bidbird-5164d.firebasestorage.app',
    iosBundleId: 'com.example.bidbird',
  );
}
